name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pytest

      # Draai tests alleen als er testbestanden zijn
      - name: Run tests (if any)
        if: ${{ hashFiles('klassement/tests/**/*.py') != '' }}
        working-directory: klassement
        run: pytest -q
